# Generated by Django 4.1.3 on 2023-01-28 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('stock', models.CharField(max_length=55)),
                ('vin', models.CharField(max_length=55)),
                ('model', models.CharField(max_length=255)),
                ('make', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.modelsaccount')),
            ],
            options={
                'verbose_name': 'Car',
            },
        ),
    ]
