# Generated by Django 4.1.3 on 2022-12-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_modelscustomer_deleted'),
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelscars',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.modelscustomer'),
        ),
    ]
