# Generated by Django 4.1.3 on 2022-11-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelscars',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
