# Generated by Django 4.1.3 on 2022-12-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_modelsaccount_status'),
        ('cars', '0003_alter_modelscars_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelscars',
            name='account',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='account.modelsaccount'),
            preserve_default=False,
        ),
    ]
