# Generated by Django 4.1.3 on 2022-12-22 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_modelsaccount_status'),
        ('cars', '0004_modelscars_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelscars',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.modelsaccount'),
        ),
    ]
