# Generated by Django 4.1.3 on 2022-12-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_modelscars_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelscars',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
