# Generated by Django 4.1.3 on 2023-01-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_modelscars_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelscars',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car'),
        ),
    ]
