# Generated by Django 4.1.3 on 2023-01-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_modelscars_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelscars',
            name='make',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
