# Generated by Django 4.1.3 on 2023-01-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_modelscars_make'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelscars',
            name='stock',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
