# Generated by Django 4.1.3 on 2022-12-24 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_modelscars_deleted'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelstask',
            name='invoice_id',
        ),
        migrations.AddField(
            model_name='modelstask',
            name='car_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.modelscars'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelstask',
            name='payment',
            field=models.IntegerField(),
        ),
    ]
