# Generated by Django 4.1.3 on 2023-04-13 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_modelsaccount_status'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelsuser',
            name='black_account_id',
        ),
        migrations.RemoveField(
            model_name='modelsuser',
            name='white_account_id',
        ),
        migrations.AddField(
            model_name='modelsuser',
            name='account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='account.modelsaccount'),
        ),
    ]
