# Generated by Django 4.1.3 on 2022-12-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_modelsaccount_status'),
        ('users', '0002_modelsuser_is_admin_alter_modelsuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsuser',
            name='account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.modelsaccount'),
        ),
        migrations.AlterField(
            model_name='modelsuser',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.modelssatus'),
        ),
    ]
