# Generated by Django 4.1.3 on 2022-11-19 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsSatusAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='modelsaccount',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.modelssatusaccount'),
        ),
    ]
