# Generated by Django 4.1.3 on 2023-01-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_modelsaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsaccount',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelsaccount',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelsaccount',
            name='hst',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelsaccount',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='account'),
        ),
        migrations.AddField(
            model_name='modelsaccount',
            name='phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelsaccount',
            name='street',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelsaccount',
            name='street1',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
