# Generated by Django 4.1.3 on 2023-01-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_modelsaccount_city_modelsaccount_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelsaccount',
            old_name='city',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='modelsaccount',
            old_name='street',
            new_name='street2',
        ),
    ]
