# Generated by Django 4.1.3 on 2022-12-25 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('cancel', 'Cancel')], default='draft', max_length=100, verbose_name='Status')),
                ('description', models.TextField(blank=True, null=True)),
                ('total_sum', models.IntegerField(blank=True, null=True)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start_date')),
                ('finished_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='End_date')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.modelscars')),
            ],
        ),
    ]
