# Generated by Django 4.1.3 on 2023-01-12 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsinvoice',
            name='crew_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelsinvoice',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.modelscustomer'),
        ),
        migrations.AddField(
            model_name='modelsinvoice',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='task.modelstask', verbose_name='task'),
        ),
    ]
