# Generated by Django 4.1.3 on 2023-03-18 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('invoice', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsinvoice',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.modelsaccount'),
            preserve_default=False,
        ),
    ]
