# Generated by Django 4.1.3 on 2022-12-24 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_modelscustomer_deleted'),
        ('invoice', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelsinvoice',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='modelsinvoice',
            name='finish',
        ),
        migrations.AddField(
            model_name='modelsinvoice',
            name='customer_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='customer.modelscustomer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelsinvoice',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='End_date'),
        ),
        migrations.AddField(
            model_name='modelsinvoice',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start_date'),
        ),
        migrations.AddField(
            model_name='modelsinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('cancel', 'Cancel')], default='draft', max_length=100, verbose_name='Status'),
        ),
    ]
