# Generated by Django 4.1.3 on 2022-12-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_modelstask_invoice_id_modelstask_car_id_and_more'),
        ('invoice', '0003_remove_modelsinvoice_create_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsinvoice',
            name='products',
            field=models.ManyToManyField(blank=True, to='task.modelstask', verbose_name='task'),
        ),
    ]
