# Generated by Django 4.1.3 on 2022-12-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_modelsinvoice_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsinvoice',
            name='total_sum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
