# Generated by Django 4.1.3 on 2022-12-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_modelsinvoice_total_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsinvoice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelsinvoice',
            name='total_sum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
