# Generated by Django 4.1.3 on 2022-12-24 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_modelsinvoice_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelsinvoice',
            old_name='products',
            new_name='tasks',
        ),
    ]
