# Generated by Django 4.1.3 on 2023-01-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_rename_products_modelsinvoice_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsinvoice',
            name='number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
