# Generated by Django 4.1.3 on 2022-12-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_modelscustomer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelscustomer',
            name='email',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
