# Generated by Django 4.1.3 on 2022-12-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_modelscustomer_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelscustomer',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
