# Generated by Django 4.1.3 on 2023-01-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_rename_address_modelscustomer_street1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelscustomer',
            name='last_name',
        ),
    ]
