# Generated by Django 4.1.3 on 2023-01-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_remove_modelscustomer_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelscustomer',
            name='phone2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modelscustomer',
            name='postal_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
