# Generated by Django 4.1.3 on 2023-01-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_modelscustomer_phone2_modelscustomer_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelscustomer',
            name='email',
            field=models.TextField(max_length=122),
        ),
    ]
